RSOsystem/RSOsystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^login/', auth_views.login,  name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),

    url(r'^rso/', include('rso.urls')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RSOsystem/rso/urls.py
from django.conf.urls import url
from . import views

# name space for urls allow us to distinguish between to urls named index or detail
app_name = 'rso'

# regular expression numbers examples
# url(r'^(?P<varName>[0-9]+[0-9]+[0-9])/$'), views.someView, 'someName')
# this would recognize a url with three digits 0 to 9 or an int from 0 to 999
# the number will be stored in "varName" and can(and should) be passed to the view.someView method
# ex) def someView(request, varName):    // this will allow you to use the value requested when handling the url



urlpatterns = [
    # /rso/
    url(r'^$', views.index, name='index'),
    # /rso/24
    # url(r'^(?P<uID>[0-9]+)/$', views.detail, name='detail'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^map/$', views.map, name='map'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^joinRso/$', views.joinRso, name='joinRso'),
    url(r'^(?P<rsoID>[0-9]+)/$', views.add, name='add'),
    url(r'^createRso/$', views.createRso, name='createRso'),

]

RSOsystem/rso/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from geoposition.fields import GeopositionField



class StudentManager(models.Manager):
    def create_student(self, user):
        student = self.create(user=user)

        return student


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student')
    university = models.ForeignKey('University', on_delete=models.CASCADE, blank=True, null=True)
    member = models.ManyToManyField('RsoGroup', blank=True)
    aboutMe = models.TextField()

    objects = StudentManager()

    def get_absolute_url(self):
        return reverse('rso:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.user.username)



class RsoGroup(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField()
    phone = models.CharField(max_length=13)
    email = models.EmailField()

    students = models.ManyToManyField(Student, related_name='rsoToStudent')

    def __str__(self):
        return self.name


class University(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField()
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    numStudents = models.IntegerField(verbose_name='Number of Student')

    def __str__(self):
        return self.name


class Event(models.Model):
    description = models.TextField()
    name = models.CharField(max_length=40)
    email = models.EmailField()
    phone = models.CharField(max_length=13)

    time = models.DateTimeField( blank=True, null=True)

    location = GeopositionField(null=True, blank=True)

    PUBLIC = 'pub'
    PRIVATE = 'pri'
    RSO = 'rso'
    visChoices = (
        (PUBLIC, 'Public Event'),
        (PRIVATE, 'Private Event'),
        (RSO, 'RSO Event'),
    )

    visibility = models.CharField(max_length=3, choices=visChoices, default=PUBLIC)

    GENERAL = 'gen'
    FUNDRAISING = 'fun'
    SOCIAL = 'soc'
    TECH = 'tec'

    catChoices = (
        (GENERAL, 'General'),
        (FUNDRAISING, 'Fund Raising'),
        (SOCIAL, 'Social'),
        (TECH, 'Tech Talk'),
    )

    category = models.CharField(max_length=3, choices=catChoices, default=GENERAL)

    rso = models.ForeignKey(RsoGroup, on_delete=models.CASCADE, blank=True, null=True, related_name='rso')
    university = models.ForeignKey(University, on_delete=models.CASCADE, related_name='university')

    def __str__(self):
        return self.name

RSOsystem/rso/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):

    first_name = forms.CharField(max_length=20, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=20, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

RSOsystem/rso/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .models import Student, RsoGroup, Event
from django.contrib.auth.models import User, Group
from rso.forms import SignUpForm
from django.contrib.auth.decorators import login_required


def index(request):
    allRSOs = RsoGroup.objects.all()

    context = {
        'allRSOs': allRSOs
    }
    return render(request, 'rso/index.html', context)


def map(request):

    events = Event.objects.filter(visibility=Event.PUBLIC)

    context = {
        'events': events,
    }

    return render(request, 'rso/map.html', context=context)


@login_required(login_url='/login/')
def profile(request):

    publicEvents = Event.objects.filter(visibility=Event.PUBLIC)
    rsoEvents = Event.objects.all()
    studentRsos = request.user.student.rsoToStudent.all()

    RSOs = RsoGroup.objects.filter(students=request.user.student)

    events = []

    for event in publicEvents:
        events.append(event)

    for event in rsoEvents:
        if event.rso in studentRsos and event not in events :
            events.append(event)

    context = {
        'events': events,
        'RSOs': RSOs,
    }

    return render(request, 'rso/profile.html', context=context)


def registration(request):

    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']

        user = User.objects.create_user(username=username, email=email)
        user.set_password(password)

        user = user.save()

        student = Student.objects.create_student(user=user)
        student.save()

        return render(request, 'rso/index.html')

    if request.method == 'GET':
        return render(request, 'rso/registration_form.html')


def signup(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            student = Student.objects.create_student(user=user)
            student.save()

            return redirect('rso:index')
    else:
        form = SignUpForm()
    return render(request, 'rso/signup.html', {'form': form})


@login_required(login_url='/login/')
def joinRso(request):

    rsos = RsoGroup.objects.all()
    return render(request, 'rso/joinRso.html', {'rsos': rsos})


@login_required(login_url='/login/')
def add(request, rsoID):

    rso = RsoGroup.objects.get(id=rsoID)
    rso.students.add(request.user.student)
    rso.save()

    rsos = RsoGroup.objects.all()
    return render(request, 'rso/joinRso.html', {'rsos': rsos})


@login_required(login_url='/login/')
def createRso(request):

    if request.method == 'POST':
        newRso = RsoGroup(
            name=request.POST['RSO_name'],
            description=request.POST['RSO_description'],
            phone=request.POST['RSO_phone'],
            email=request.POST['RSO_email']
        )

        allRSOs = RsoGroup.objects.all()

        context = {
            'allRSOs': allRSOs
        }

        creator = User.objects.get(username=request.user.username)
        creator.is_staff = True

        admins = Group.objects.get(name='Admin')
        creator.groups.add(admins)

        newRso.save()
        newRso.students.add(creator.student)
        newRso.save()


        creator.save()

        return render(request, 'rso/index.html', context=context    )

    return render(request, 'rso/createRso.html')

RSOsystem/rso/templates/rso/base.html
<html>

<head>
    <title>{% block title %}{% endblock %}</title>


    <!-- bootstrap links -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'rso/style.css' %}" />
</head>

<body>

  <nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rso:index'  %}">RSO</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><a href="{% url 'rso:profile' %}">Profile<span class="sr-only">(current)</span></a></li>

        <li><a href="{% url 'rso:map' %}">Event Map</a></li>

        <li><a href="{% url 'rso:joinRso' %}">Join RSOs</a></li>

        <li><a href="{% url 'rso:createRso' %}">Create RSO</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li>
              <a href="{% url 'rso:profile' %}">{{ request.user.username }}</a>
            </li>
            <li>
              <a href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'rso:signup' %}">Sigh Up</a>
            </li>
          {% endif %}
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  <div id="sidePanel" class="col-md-2"></div>

  <div style="min-height: 800px" class="panel panel-default col-md-8 center-panel">
    <div class="centerPanel">
        {% block content %}
        {% endblock content %}
    </div>
  </div>

  <div id="sidePanel" class="col-md-2"></div>

</body>

</html>

RSOsystem/rso/templates/rso/createRso.html
{% extends 'rso/base.html' %}
{% block title %}Login{% endblock %}

{% block content %}

    <div class="container" id="RSO-container">

        <div class="row">



            <div class="col-md-2"></div>
            <div class="col-md-6">

                <div class="panel panel-default">

                    <div class="panel-heading panel-heading-custom">Create a New RSO</div>

                    <div class="panel-body">
                        <form id="RSO-form" method="post"
                              action="">

                            {% csrf_token %}

                            <div class="form-group">
                                <label for="RSO_name">RSO Name</label>
                                <input id="RSO_name" name="RSO_name"
                                       type="text" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="RSO_description">RSO Description</label>
                                <input id="RSO_description" name="RSO_description"
                                       type="text" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="RSO_phone">RSO Phone Number</label>
                                <input id="RSO_phone" name="RSO_phone"
                                       type="text" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="RSO_email">RSO email</label>
                                <input id="RSO_email" name="RSO_email"
                                       type="text" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="id_email_one">Email One</label>
                                <input id="id_email_one" name="email_one"
                                       type="email" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="id_email_two">Email Two</label>
                                <input id="id_email_two" name="email_two"
                                       type="email" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="id_email_three">Email Three</label>
                                <input id="id_email_three" name="email_three"
                                       type="email" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="id_email_four">Email Four</label>
                                <input id="id_email_four" name="email_four"
                                       type="email" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="id_email_five">Email Five</label>
                                <input id="id_email_five" name="email_five"
                                       type="email" class="form-control">
                            </div>
                {% if form.errors %}
                    <p class=" label label-danger">

                    </p>
                {% endif %}
                            <input type="submit" value="Create RSO"
                                   class="btn btn-primary pull-right" />
                            <input type="hidden" name="next" value="{{ next }}" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

RSOsystem/rso/templates/rso/detail.html
{% extends 'rso/base.html' %}

{% block title %}Details{% endblock %}

{% block content %}
	<h3>Student Data</h3>
    <h2>student ID: {{ id }}</h2>
    <h2>student FirstName: {{ first_name }}</h2>
    <h2>student LastName: {{ last_name }}</h2>
    <h2>student Email: {{ email }}</h2>
{% endblock %}

RSOsystem/rso/templates/rso/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-lable col-sm-2">{{ field.lable_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

RSOsystem/rso/templates/rso/index.html
{% extends 'rso/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <div class="col-md-1">
    </div>

    <div style="padding-top: 20px" class="col-md-10">
        <div class="panel panel-default">
            <div  class="panel-heading panel-heading-custom">All RSO Groups</div>

            {% if allRSOs %}
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="row"></th>
                                <td><b>RSO Name</b></td>
                                <td><b>Description</b></td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for rso in allRSOs %}
                                <tr>
                                    <th scope="row"></th>
                                    <td>{{ rso.name }}</td>
                                    <td>{{ rso.description }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="panel-body">There are no RSOs.</div>
            {% endif %}

        </div>
    </div>
{% endblock %}

RSOsystem/rso/templates/rso/joinRso.html
{% extends 'rso/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}

    {% if rsos %}
        {% for rso in rsos %}
            <div class="row">
                <div class="col-md-1"></div>

                <div style="padding-top: 20px" class="col-md-10">
                    <div class="panel panel-default">
                        <div  class="panel-heading panel-heading-custom">All RSO Groups</div>
                        <div class="panel-body">
                            <p>{{ rso.description }}</p>
                            {% csrf_token %}
                            <p><a href="{% url 'rso:add' rso.id %}">Join this RSO</a></p>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-md-1">
            </div>
            <div style="padding-top: 20px" class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading panel-heading-custom">All RSO Groups</div>
                    <div class="panel-body">
                        <p>There are no RSOs yet.</p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

RSOsystem/rso/templates/rso/map.html
{% extends 'rso/base.html' %}
{% block title %}Map{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-lg-12">
            <h3 style="color: white;">Map of RSO Events</h3>
            <div id="map"></div>
            <script>
                function initMap() {
                    var UCF = {lat: 28.6024, lng: -81.2001};
                    var map = new google.maps.Map(document.getElementById('map'), {
                        zoom: 13,
                        center: UCF,
                    });

                    {% for event in events %}
                        var point = new google.maps.LatLng({{ event.location.latitude }}, {{ event.location.longitude }});

                        var marker = new google.maps.Marker({
                            position: point,
                            map: map,
                        });

                    {% endfor %}
                }
            </script>

            <script async defer
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCTp8QRWk07T9zGGSA3Z6wAy_BH0yi5LQs&callback=initMap">
            </script>




            <div class="col-md-1">
            </div>

            <div style="padding-top: 20px" class="col-md-10">
                <div class="panel panel-default">
                    <div  class="panel-heading panel-heading-custom">Public Events</div>

                    {% if events %}
                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="row"></th>
                                        <td><b>Event Name</b></td>
                                        <td><b>Description</b></td>
                                        <td>Where</td>
                                        <td>When</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for event in events %}
                                        <tr>
                                            <th scope="row"></th>
                                            <td>{{ event.name }}</td>
                                            <td>{{ event.description }}</td>
                                            <td>{{ event.location }}</td>
                                            <td>{{ event.time }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <div class="panel-body">There are no events.</div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>












{% endblock %}

RSOsystem/rso/templates/rso/profile.html
{% extends 'rso/base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div style="padding-bottom: 20px;" class="col-md-12"></div>
        </div>

        <div class="row">

            <div class="col-md-5">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-custom">About {{ request.user.username }} </div>
                        <div style="min-height: 150px;" class="panel-body">
                            <p>{{ request.user.student.aboutMe }}</p>
                        </div>

                    </div>

            </div>

            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading panel-heading-custom">Your RSOs</div>
                    <div style="min-height: 150px;" class="panel-body">

                        {% if RSOs %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="row"></th>
                                    <td>RSO Name</td>
                                    <td>Description</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for rso in RSOs %}
                                    <tr>
                                        <th scope="row"></th>
                                        <td>{{ rso.name }}</td>
                                        <td>{{ rso.description }}</td>
                                    </tr>
                                {% endfor %}
                                <th scope=""></th>
                            </tbody>
                        </table>
                        {% else %}
                            <div class="panel-body">Not a member of any RSOs yet.</div>
                        {% endif %}

                    </div>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading panel-heading-custom">Your Info</div>
                    <div class="panel-body">
                        <p><b>User Name</b>: {{ request.user.username }}</p>
                        <p><b>First Name</b>: {{ request.user.first_name }}</p>
                        <p><b>Last Name</b>: {{ request.user.last_name }}</p>
                        <p><b>University</b>: {{ request.user.student.university }}</p>
                        <p><b>Email</b>: {{ request.user.email }}</p>
                        <p><b>Date Joined</b>: {{ request.user.date_joined }}</p>

                    </div>

                </div>
            </div>
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading panel-heading-custom">Events</div>
                    <div class="panel-body">


                    {% if events %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="row"></th>
                                    <td>Event Name</td>
                                    <td>Description</td>
                                    <td>Address</td>
                                    <td>RSO</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                    <tr>
                                        <th scope="row"></th>
                                        <td>{{ event.name }}</td>
                                        <td>{{ event.description }}</td>
                                        <td>{{ event.address}}</td>
                                        <td>{{ event.rso.name }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            <div class="panel-body">No events.</div>
                        {% endif %}









                    </div>
                </div>

            </div>
        </div>

    </div>


{% endblock %}

RSOsystem/rso/templates/rso/registration_form.html
{% extends 'rso/base.html' %}
{% block title %}Register{% endblock %}

{% block content %}

{##}
{#    <div id="registration-form">#}
{#        <div class="container">#}


    <div class="col-lg-4"></div>
    <div id="content-container" class="container p-none">
        <div class="panel panel-default lgn-container col-lg-4">
            <form id="login-form" method="post"
                  action="{% url 'rso:registration' %}">
                {% csrf_token %}
                
                <div class="form-group">

                        <label for="id_email">Email</label>
                        <input id="id_email" name="email" 
                                   type="email" class="form-control" placeholder="Email Address">
                </div>
                <div class="form-group">

                        <label for="id_username">Username</label>
                        <input id="id_username" name="username" 
                                   type="text" class="form-control" placeholder="username">
                </div>
                <div class="form-group">
                        <label for="id_password">Password</label>
                        <input id="id_password" name="password" 
                                   type="password" class="form-control" placeholder="password">
                </div>
                
                    {% if form.errors %}
                        <p class=" label label-danger">
                            Your username and password didn't match. 
                            Please try again.
                        </p>
                    {% endif %}

                    <input type="submit" value="Sign Up"
                           class="btn btn-primary pull-right" />
                    <input type="hidden" name="next" value="{{ next }}" />
                
            </form>
            </div>
        </div>
    </div>
{% endblock content %}

RSOsystem/rso/templates/rso/signup.html
{% extends 'rso/base.html' %}
{% block title %}Sign Up{% endblock %}


{% block content %}

    <div style="padding-top: 20px;" class="row">
        <div class="col-md-4"></div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading panel-heading-custom">
                    <h4>Sign up</h4>
                </div>
                <div class="panel-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit">Sign up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

RSOsystem/rso/templates/rso/student_form.html
{%  extends 'rso/base.html' %}
{% block title %}Add Student{% endblock %}

{% block content %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-boddy">

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'rso/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}